# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=150)),
                ('status', models.TextField(blank=True)),
                ('accessed', models.IntegerField(blank=True, default=0, null=True)),
                ('command', models.TextField(blank=True)),
            ],
        ),
    ]
